# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-31 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=5)),
                ('offcURL', models.URLField(unique=True)),
                ('offctwttr', models.URLField(unique=True)),
            ],
        ),
    ]
